### ISSUE TITLE
Destructuring assignment support

### ISSUE THREAD

**Issue by wqweto** [twinbasic/lang-design#28]
**Is your feature request related to a problem? Please describe.**
The problem being solved is returning more that one result like in modern languages like in golang we have
```
    max, min = maxmin(a, b)
```
. . . or for error handling with
```
    message, err := greetings.Hello("")
    if err != nil {
        log.Fatal(err)
    }
```

**Describe the solution you'd like**
I would like to be able ot destructure a SAFEARRAY in TB like this
```
    Array(message, err) = greetings.Hello("World!")
```
. . . which may benefit from support on the other side like this
```
Function Hello(sText As String) As Variant
    Dim sError As String
    . . .
    Return "Hello " & sText, sError
End Function
```
. . . but this is a syntatic sugar for `Return Array("Hello " & sText, "No Error")` so not that necessary

The idea is for a new `Array` statement to be used on the LHS of assignment like we already have `Mid` statement overloading the same named function.

**Describe alternatives you've considered**
An alternative would be real tuples support outside of OLE Automation data-types.

**Comment by WaynePhillipsEA** [comment]
It's an interesting idea!  And feels very much alike the Mid statement, as you mentioned.

For now I'll just mention twinbasic/lang-design#14, as we discussed the idea of tuples briefly before.

**Comment by wqweto** [comment]
@WaynePhillipsEA Can we move this proposal to lang-design?

**Comment by mburns08109** [comment]
All,

I'm going to vote a loud NO on this proposal (assuming that there's still time for this to matter).
I'll cite the following reasons:
1) It's definitely "un-BASICy"
2) according to comments above, it is both limited in terms of type safety, and a "less than ideal" approach compared to full support for tupples (which Wayne has already indicated is most likely to be a v2 item).
3) might it not represent a possible "hackery" risk since there are "type safety" issue afoot with this idea in its present form?
4) there are already more than adequate workaround for this in the existing language - UDTs and arrays were specifically mentioned earlier in the conversation.
5) i really dislike the idea of overloading Array for this - semantically, at least it would seem to me that ParamArray() would be a better fit for the proposed usage (to accept "n" multiple return values from a function) - that usage would at least be semantically consistent with what ParamArrays already do - only on the feeding into the function side. This would do much the same on the output from the function side, so there's at least some semantic symmetry there. (An additional advantage here is that nobody expects ParamArrays to "stick around" as a data structure after it's been used.)
6) don't let the desire to be lazier in typing fewer things (or the fact that it may be fairly easy to implement) lead us into doing something sloppier and for inadequate reasons given the likely future support for tupples in v1+. Remember that patience is a virtue.

Better to await the tupple support in v2 than to "de-BASIC-ize" tB with this mediocre approach to the problem that isn't _really_ that much of a problem given very workable alternatives already in hand.

**Comment by wqweto** [comment]
@mburns08109 You already stated your moot “fears” no need to repeat them.

The proposal is fine, simple, elegant and quite clever I might add.

Will debunk your points one by one later if time permits.

**Comment by WaynePhillipsEA** [comment]
This is now supported via the `Array(var1, var2) = anArray` syntax.  e.g. `Array(, varA, ,varB) = Array(1,2,3,4)` would set `varA = 2` and `varB = 4`.   Requires BETA 416.

**Comment by Greedquest** [comment]
Does `Array(Array(a,b),Array(c,d)) = Range("A1:B2")` work? Also python does a neat trick with a trailing comma to indicate no additional elements `a, b, = foo()` meaning if foo does not return exactly 2 elements then an error is thrown, but maybe that can wait

**Comment by wqweto** [comment]
Nested destructuring seems supported by php too: https://blog.frankdejonge.nl/array-destructuring-in-php/
